#!/bin/bash
cd $(dirname $0)
project_name="synthetic-exchange"
if [ "${CONDA_EXE} " == " " ]; then
    CONDA_EXE=$((find /opt/conda/bin/conda || find ~/anaconda3/bin/conda || \
        find /usr/local/anaconda3/bin/conda || find ~/miniconda3/bin/conda  || \
        find /root/miniconda/bin/conda || find ~/Anaconda3/Scripts/conda) 2>/dev/null)
fi
if [ "${CONDA_EXE}_" == "_" ]; then
    echo "Please install Anaconda w/ Python 3.7+ first"
    echo "See: https://www.anaconda.com/distribution/"
    exit 1
fi
CONDA_BIN=$(dirname ${CONDA_EXE})
MACOS_ENV=""
WIN64_ENV=""
LINUX_ENV=setup/environment-linux.yml
ENV_FILE=$LINUX_ENV
if uname | egrep -qe "Linux"; then
    ENV_FILE=$LINUX_ENV
else
	echo "OS env not supported"
	exit 1
fi
if ${CONDA_EXE} env list | egrep -qe "^${project_name}"; then
    ${CONDA_EXE} env update -f $ENV_FILE
else
    ${CONDA_EXE} env create -f $ENV_FILE
fi
source "${CONDA_BIN}/activate" ${project_name}
pip install objgraph
pre-commit install
